### ISSUE TITLE
I can't use the @ letters because they are covered by other extensions.

### ISSUE THREAD

**Issue by null0516** [cheald/sd-webui-loractl#14]
I am using @ in the syntax with this sdweb-easy-prompt-selector extension, so I cannot use @ due to interference.
Could you please do something about this?

https://github.com/blue-pen5805/sdweb-easy-prompt-selector

**Comment by cheald** [comment]
Hm. I'm not too wild about bending over backwards to fix an over-aggressive parser from another extension, but we could add a second alternate character that could be used rather than the "@" as a workaround. Do you have a suggestion for what would work best?

**Comment by null0516** [comment]
Sorry to be so unreasonable.
Both extensions are great for me.

How about something like "$"?
I am not at all familiar with the syntax rules of the program, so it is a random suggestion.

**Comment by cheald** [comment]
I've added `~` as an alternate delimiter:

    <lora:network:0~0,0.5~1>
