### ISSUE TITLE
Suggestion: Add "Enable" checkbox

### ISSUE THREAD

**Issue by Kansaku** [cheald/sd-webui-loractl#16]
Hey,

I really like this extension and its fun to play with it  <3

Would it be possible to add a "Enable" Checkbox to activate/deactivate the plugin on the fly in Automatics UI?
I like to switch between this and Lora Block Weight extension to try stuff, but this extension disables the functionality of the Lora Block Weight extension.

![Screenshot 2023-08-19 211611](https://github.com/cheald/sd-webui-loractl/assets/130408703/0e1a2bbf-8a39-4468-8e43-370e9a194132)

Like this^^ to be able to switch between this and other Lora affecting extensions without the need to seperately disable/enable them in the extensions tab and reloading the whole instance.

**Comment by cheald** [comment]
Sure, that's easy enough. Done in 9b19512dd60861352b4a469a5d221354082f7243
