### ISSUE TITLE
cant use with more than 1 lora

### ISSUE THREAD

**Issue by Kgbaslanii** [cheald/sd-webui-loractl#18]
when i try to use with more than 1 lora it only affects the first lora in prompt
![tmpgtyfbu8u](https://github.com/cheald/sd-webui-loractl/assets/112936137/02b0ba66-b3fe-47d2-be38-c0fa4f0934cd)
(<lora:Loraeyes_V1:0@0, 1@0.4> <lora:3DMM_V5:1@0, 0.5@0.5> <lora:add_detail:1@0, 0.2@1> mechanical bird)
problem could be the last update my existing seeds started giving different results

**Comment by Corenovamc** [comment]
same problem after of updating, I hope it will be solved soon, thanks!

**Comment by cheald** [comment]
Whoops. I introduced that bug with another fix last night. 046ad79818dc7f4dbf71dbaea430383e2e5ee21b should fix it.
