### ISSUE TITLE
LoRA uncontrollable weight on HiRes Fix prompts.

### ISSUE THREAD

**Issue by DavideAlidosi** [cheald/sd-webui-loractl#2]
The weight of LoRAs is always applied to 1 when applied within the HiRes Fix prompts.
To replicate the bug:
1) activate from preferences: hires fix: show hires prompt and negative prompt.
2) enter a LoRA in the promt of the Hires fix function.

**Comment by cheald** [comment]
I think this is now fixed; there was a more general issue with the defaulting of highres pass weights. Let me know if this is still happening.
