### ISSUE TITLE
Composable Lora issue (maybe not your issue)

### ISSUE THREAD

**Issue by altoiddealer** [cheald/sd-webui-loractl#29]
Hello, I just wanted to bring this to your attention... or maybe I'm doing something wrong?
I believe I'm using the correct syntax.

![2023-12-23_09-41-08_0](https://github.com/cheald/sd-webui-loractl/assets/1613484/cfb24f73-ceb5-4431-a7ee-4605cdf17c72)

Prompt:
```
A massive and intricate sculpture of a mushroom cloud, <lora:mushroom_cloud:1.0@0.0,0.5@0.5>, but instead of smoke or fire it's made out of honey, made of dvr-honey, <lora:HoneyStyle:0.5@0.0,1.0@0.5>. The colors are warm golden hues and the sculpture is surrounded by bees buzzing around, creating a surreal yet beautiful scene
```

I'm up to date with the current stable version of Stable Diffusion, and sd-webui-loractl.

I get the following error in my SD cmd window:

```
*** Error running process: C:\0_SD\sd.webui\webui\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py
    Traceback (most recent call last):
      File "C:\0_SD\sd.webui\webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\0_SD\sd.webui\webui\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py", line 54, in process
        composable_lora.load_prompt_loras(prompt)
      File "C:\0_SD\sd.webui\webui\extensions\stable-diffusion-webui-composable-lora\composable_lora.py", line 19, in load_prompt_loras
        multiplier = float(params.items[1]) if len(params.items) > 1 else 1.0
    ValueError: could not convert string to float: '1.0@0.0,0.5@0.5'
```

**Comment by altoiddealer** [comment]
I'm following up to say - I noticed I was on an older fork of Composable Lora (I saw that you replied to someone else [linking to a newer one](https://github.com/a2569875/stable-diffusion-webui-composable-lora))

However, even after switching over I still have the same error

**Comment by altoiddealer** [comment]
I'm guessing the correct thing to do, is just don't use composable LORA in conjunction with loractl :)

**Comment by cheald** [comment]
In this case, composable_lora is trying to parse a positional parameter as an int, but can't because it has the loractl syntax.

You could try specifying the lora as <lora:name:te=...> to move it to a named parameter. This may not fix it if composable_lora is also trying to read named parameters, though.
