### ISSUE TITLE
Feauture request: ComfyUI Implementation?

### ISSUE THREAD

**Issue by OliviaOliveiira** [cheald/sd-webui-loractl#30]
Hey there! 
Can you by any chance implement the logic into a ComfyUI node?

**Comment by cheald** [comment]
This implementation is very specific to automatic's implementation of LoRAs; the same concept might be applicable in comfy, but it'll depend a lot on the internals of how networks are implemented. I haven't looked at ComfyUI enough to be able to make any kind of assessment as to its feasibility. A ComfyUI implementation would need to be a full separate project (and I encourage anyone with the impetus to do it!), but I don't have it on my plate right now.
