### ISSUE TITLE
How to load lora diretly? 

### ISSUE THREAD

**Issue by jiaxiangc** [cheald/sd-webui-loractl#34]
I want to load lora from lora path directly in webui? do you know how to code it 
thanks

**Comment by cheald** [comment]
This question is out of scope for this project, but I suggest that you look at the Lora/networks.py file in A1111 for the lora loading routine.

**Comment by jiaxiangc** [comment]
@cheald I am looking forward to a help. I have a plugin about adapting diffusion model resolution. https://github.com/bytedance/res-adapter
I have make [ComfyUI Node](https://github.com/jiaxiangc/ComfyUI-ResAdapter), but I am new to webui. It is difficult for me to understand lora load in A1111 repo.
Can you give me detailed advice or guidance about lora load function. (Just a minimal function to load lora for diffusion_model).

**Comment by cheald** [comment]
This is a question better asked on the A1111 repo. This extension doesn't deal with loading loras.

**Comment by jiaxiangc** [comment]
Thanks for your advice.
