### ISSUE TITLE
IS composable lora clashing with lora CTL?

### ISSUE THREAD

**Issue by rafstahelin** [cheald/sd-webui-loractl#35]
Just wondering if composable lora clashing with lora CTL?

I am getting this error in console when inferring:
`Traceback (most recent call last):
      File "E:\auto1111\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "E:\auto1111\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py", line 133, in process
        composable_lora.load_prompt_loras(prompt)
      File "E:\auto1111\extensions\stable-diffusion-webui-composable-lora\composable_lora.py", line 111, in load_prompt_loras
        multiplier = float(params.items[1]) if len(params.items) > 1 else 1.0
    ValueError: could not convert string to float: '0@0,1@0.4'
`
The CTL inference syntax does still give me an image but wondered if it was necessary to remove the composable lora extension?

**Comment by cheald** [comment]
It can't handle non-numeric weight syntax, which loractl supports. It's trying to interpret the complex weight syntax as a float and chokes because it's unable to do so. It's likely just not functioning.

**Comment by rafstahelin** [comment]
Just disabled composable lora. working nowraf stahelinOn 12 Apr 2024, at 16:18, Chris Heald ***@***.***> wrote:﻿
It can't handle non-numeric weight syntax, which loractl supports. It's trying to interpret the complex weight syntax as a float and chokes because it's unable to do so. It's likely just not functioning.
